# SPDX-FileCopyrightText: Copyright (c) M. Boerger, the MBO Works authors
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@rules_shell//shell:sh_library.bzl", "sh_library")

package(default_visibility = ["//visibility:private"])

bzl_library(
    name = "bashtest_bzl",
    srcs = ["bashtest.bzl"],
)

sh_library(
    name = "bashtest_sh",
    srcs = ["bashtest.sh"],
    visibility = ["//visibility:public"],
)

alias(
    name = "bashtest",
    actual = ":bashtest_sh",
    visibility = ["//visibility:public"],
)

genrule(
    name = "bashtest_help",
    testonly = 1,
    srcs = ["bashtest.sh"],
    outs = ["bashtest_help.sh"],
    cmd = """
    echo "#!/usr/bin/env bash" >$@
    echo "bash $< --help || true" >>$@
    """,
    executable = 1,
    tags = ["manual"],
    visibility = ["//visibility:private"],
)

genrule(
    name = "bashtest_help_md",
    testonly = 1,
    srcs = ["bashtest.sh"],
    outs = ["bashtest_help.md"],
    cmd = """bash $< --help >$@ || true""",
    tags = ["manual"],
    visibility = ["//visibility:private"],
)
